print("\nAGENT SPECIALIZATION:")
print("="*60)
print("\nGrowthAgent learned to favor:")
print("  • NVDA (semiconductors)")
print("  • AMD, AVGO (high-growth)")
print("  • Strategy: Aggressive, high-beta stocks")
print("  • Result: 11.45% return, 1.198 Sharpe")
print("  • Works in: Bull markets\n")

print("ValueAgent learned to favor:")
print("  • MSFT, GOOGL, AMZN (mega-caps)")
print("  • NOW, CRM (stable enterprise)")
print("  • Strategy: Conservative allocation")
print("  • Result: 17.77% return, 1.995 Sharpe ⭐")
print("  • Works in: This test period (moderate volatility)\n")

print("RiskAgent learned:")
print("  • Equal diversification")
print("  • Maximum position: 15%")
print("  • Strategy: Risk parity")
print("  • Result: 16.52% return, 1.791 Sharpe")
print("  • Works in: Volatile markets\n")

print("Orchestrator learned:")
print("  • Blend Value + Risk in current market")
print("  • Avoid over-weighting Growth")
print("  • Result: 15.93% return, 1.707 Sharpe")
print("  • Demonstrates coordination")
